### ISSUE TITLE
Documentation to setup discord bot on discord developer portal

### ISSUE THREAD

**Issue by milan090** [milan090/simple-discord-music-bot#2]
Edit README to include this documentation.

**Comment by MaximeKoitsalu** [comment]
Hey @milan090 I could take on this task :)

**Comment by milan090** [comment]
@MaximeKoitsalu sure, go ahead.

**Comment by MaximeKoitsalu** [comment]
@milan090 Added a new readme file with instructions as per your request. Hope that's what you asked for 😊

**Comment by milan090** [comment]
@MaximeKoitsalu Great! It's almost done. I've requested few necessary changes. Do address them soon and i'll merge the request
